spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_simple_tutorial?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&useSSL=true
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
